services:
  - type: web
    name: pixel-qa-checker
    env: python
    buildCommand: "./post_build.sh"
    startCommand: "streamlit run src/pixel_qa_ui_with_validation.py"
    buildFilter:
      paths:
        - "**/*"
